Add check for [incr Tcl] in configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4830,6 +4830,17 @@ else
   exit 1
 fi
 
+# Check for Itcl
+echo -n 'checking for [incr Tcl]... '
+if echo 'exit [catch {package require Itcl}]' | tclsh; then
+  echo 'yes'
+else
+  echo 'no'
+  echo 'Tcl cannot find the [incr Tcl] (also known as Itcl) library.'
+  echo 'Make sure that Itcl (at least version 3.4) is installed.'
+  exit 1
+fi
+
 # Checks for libraries.
 ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
